/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedDaybookRouteImport } from './routes/_authenticated/daybook'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedTransferIndexRouteImport } from './routes/_authenticated/transfer.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedIncomingIndexRouteImport } from './routes/_authenticated/incoming.index'
import { Route as AuthenticatedFinancesIndexRouteImport } from './routes/_authenticated/finances.index'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsPreferencesRouteImport } from './routes/_authenticated/settings.preferences'
import { Route as AuthenticatedIncomingIdRouteImport } from './routes/_authenticated/incoming.$id'
import { Route as AuthenticatedFinancesLedgersIdRouteImport } from './routes/_authenticated/finances.ledgers.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDaybookRoute = AuthenticatedDaybookRouteImport.update({
  id: '/daybook',
  path: '/daybook',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransferIndexRoute =
  AuthenticatedTransferIndexRouteImport.update({
    id: '/transfer/',
    path: '/transfer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncomingIndexRoute =
  AuthenticatedIncomingIndexRouteImport.update({
    id: '/incoming/',
    path: '/incoming/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancesIndexRoute =
  AuthenticatedFinancesIndexRouteImport.update({
    id: '/finances/',
    path: '/finances/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPreferencesRoute =
  AuthenticatedSettingsPreferencesRouteImport.update({
    id: '/settings/preferences',
    path: '/settings/preferences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncomingIdRoute = AuthenticatedIncomingIdRouteImport.update({
  id: '/incoming/$id',
  path: '/incoming/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancesLedgersIdRoute =
  AuthenticatedFinancesLedgersIdRouteImport.update({
    id: '/finances/ledgers/$id',
    path: '/finances/ledgers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/daybook': typeof AuthenticatedDaybookRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/finances/': typeof AuthenticatedFinancesIndexRoute
  '/incoming/': typeof AuthenticatedIncomingIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/transfer/': typeof AuthenticatedTransferIndexRoute
  '/finances/ledgers/$id': typeof AuthenticatedFinancesLedgersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/daybook': typeof AuthenticatedDaybookRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/finances': typeof AuthenticatedFinancesIndexRoute
  '/incoming': typeof AuthenticatedIncomingIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/transfer': typeof AuthenticatedTransferIndexRoute
  '/finances/ledgers/$id': typeof AuthenticatedFinancesLedgersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/daybook': typeof AuthenticatedDaybookRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/_authenticated/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/finances/': typeof AuthenticatedFinancesIndexRoute
  '/_authenticated/incoming/': typeof AuthenticatedIncomingIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/transfer/': typeof AuthenticatedTransferIndexRoute
  '/_authenticated/finances/ledgers/$id': typeof AuthenticatedFinancesLedgersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/daybook'
    | '/people'
    | '/incoming/$id'
    | '/settings/preferences'
    | '/settings/profile'
    | '/finances/'
    | '/incoming/'
    | '/settings/'
    | '/transfer/'
    | '/finances/ledgers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/daybook'
    | '/people'
    | '/incoming/$id'
    | '/settings/preferences'
    | '/settings/profile'
    | '/finances'
    | '/incoming'
    | '/settings'
    | '/transfer'
    | '/finances/ledgers/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/analytics'
    | '/_authenticated/daybook'
    | '/_authenticated/people'
    | '/_authenticated/incoming/$id'
    | '/_authenticated/settings/preferences'
    | '/_authenticated/settings/profile'
    | '/_authenticated/finances/'
    | '/_authenticated/incoming/'
    | '/_authenticated/settings/'
    | '/_authenticated/transfer/'
    | '/_authenticated/finances/ledgers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daybook': {
      id: '/_authenticated/daybook'
      path: '/daybook'
      fullPath: '/daybook'
      preLoaderRoute: typeof AuthenticatedDaybookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfer/': {
      id: '/_authenticated/transfer/'
      path: '/transfer'
      fullPath: '/transfer/'
      preLoaderRoute: typeof AuthenticatedTransferIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incoming/': {
      id: '/_authenticated/incoming/'
      path: '/incoming'
      fullPath: '/incoming/'
      preLoaderRoute: typeof AuthenticatedIncomingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/': {
      id: '/_authenticated/finances/'
      path: '/finances'
      fullPath: '/finances/'
      preLoaderRoute: typeof AuthenticatedFinancesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/preferences': {
      id: '/_authenticated/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incoming/$id': {
      id: '/_authenticated/incoming/$id'
      path: '/incoming/$id'
      fullPath: '/incoming/$id'
      preLoaderRoute: typeof AuthenticatedIncomingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances/ledgers/$id': {
      id: '/_authenticated/finances/ledgers/$id'
      path: '/finances/ledgers/$id'
      fullPath: '/finances/ledgers/$id'
      preLoaderRoute: typeof AuthenticatedFinancesLedgersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDaybookRoute: typeof AuthenticatedDaybookRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedIncomingIdRoute: typeof AuthenticatedIncomingIdRoute
  AuthenticatedSettingsPreferencesRoute: typeof AuthenticatedSettingsPreferencesRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedFinancesIndexRoute: typeof AuthenticatedFinancesIndexRoute
  AuthenticatedIncomingIndexRoute: typeof AuthenticatedIncomingIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTransferIndexRoute: typeof AuthenticatedTransferIndexRoute
  AuthenticatedFinancesLedgersIdRoute: typeof AuthenticatedFinancesLedgersIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDaybookRoute: AuthenticatedDaybookRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedIncomingIdRoute: AuthenticatedIncomingIdRoute,
  AuthenticatedSettingsPreferencesRoute: AuthenticatedSettingsPreferencesRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedFinancesIndexRoute: AuthenticatedFinancesIndexRoute,
  AuthenticatedIncomingIndexRoute: AuthenticatedIncomingIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTransferIndexRoute: AuthenticatedTransferIndexRoute,
  AuthenticatedFinancesLedgersIdRoute: AuthenticatedFinancesLedgersIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
