/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated/finances'
import { Route as AuthenticatedDaybookRouteImport } from './routes/_authenticated/daybook'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedTransferIndexRouteImport } from './routes/_authenticated/transfer.index'
import { Route as AuthenticatedStorageIndexRouteImport } from './routes/_authenticated/storage.index'
import { Route as AuthenticatedIncomingIndexRouteImport } from './routes/_authenticated/incoming.index'
import { Route as AuthenticatedGradingIndexRouteImport } from './routes/_authenticated/grading.index'
import { Route as AuthenticatedStorageIdRouteImport } from './routes/_authenticated/storage.$id'
import { Route as AuthenticatedIncomingIdRouteImport } from './routes/_authenticated/incoming.$id'
import { Route as AuthenticatedGradingIdRouteImport } from './routes/_authenticated/grading.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDaybookRoute = AuthenticatedDaybookRouteImport.update({
  id: '/daybook',
  path: '/daybook',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransferIndexRoute =
  AuthenticatedTransferIndexRouteImport.update({
    id: '/transfer/',
    path: '/transfer/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStorageIndexRoute =
  AuthenticatedStorageIndexRouteImport.update({
    id: '/storage/',
    path: '/storage/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncomingIndexRoute =
  AuthenticatedIncomingIndexRouteImport.update({
    id: '/incoming/',
    path: '/incoming/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGradingIndexRoute =
  AuthenticatedGradingIndexRouteImport.update({
    id: '/grading/',
    path: '/grading/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStorageIdRoute = AuthenticatedStorageIdRouteImport.update({
  id: '/storage/$id',
  path: '/storage/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncomingIdRoute = AuthenticatedIncomingIdRouteImport.update({
  id: '/incoming/$id',
  path: '/incoming/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGradingIdRoute = AuthenticatedGradingIdRouteImport.update({
  id: '/grading/$id',
  path: '/grading/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/daybook': typeof AuthenticatedDaybookRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/grading/$id': typeof AuthenticatedGradingIdRoute
  '/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/storage/$id': typeof AuthenticatedStorageIdRoute
  '/grading/': typeof AuthenticatedGradingIndexRoute
  '/incoming/': typeof AuthenticatedIncomingIndexRoute
  '/storage/': typeof AuthenticatedStorageIndexRoute
  '/transfer/': typeof AuthenticatedTransferIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/daybook': typeof AuthenticatedDaybookRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/grading/$id': typeof AuthenticatedGradingIdRoute
  '/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/storage/$id': typeof AuthenticatedStorageIdRoute
  '/grading': typeof AuthenticatedGradingIndexRoute
  '/incoming': typeof AuthenticatedIncomingIndexRoute
  '/storage': typeof AuthenticatedStorageIndexRoute
  '/transfer': typeof AuthenticatedTransferIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/daybook': typeof AuthenticatedDaybookRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/grading/$id': typeof AuthenticatedGradingIdRoute
  '/_authenticated/incoming/$id': typeof AuthenticatedIncomingIdRoute
  '/_authenticated/storage/$id': typeof AuthenticatedStorageIdRoute
  '/_authenticated/grading/': typeof AuthenticatedGradingIndexRoute
  '/_authenticated/incoming/': typeof AuthenticatedIncomingIndexRoute
  '/_authenticated/storage/': typeof AuthenticatedStorageIndexRoute
  '/_authenticated/transfer/': typeof AuthenticatedTransferIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/daybook'
    | '/finances'
    | '/people'
    | '/settings'
    | '/grading/$id'
    | '/incoming/$id'
    | '/storage/$id'
    | '/grading/'
    | '/incoming/'
    | '/storage/'
    | '/transfer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/daybook'
    | '/finances'
    | '/people'
    | '/settings'
    | '/grading/$id'
    | '/incoming/$id'
    | '/storage/$id'
    | '/grading'
    | '/incoming'
    | '/storage'
    | '/transfer'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/analytics'
    | '/_authenticated/daybook'
    | '/_authenticated/finances'
    | '/_authenticated/people'
    | '/_authenticated/settings'
    | '/_authenticated/grading/$id'
    | '/_authenticated/incoming/$id'
    | '/_authenticated/storage/$id'
    | '/_authenticated/grading/'
    | '/_authenticated/incoming/'
    | '/_authenticated/storage/'
    | '/_authenticated/transfer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daybook': {
      id: '/_authenticated/daybook'
      path: '/daybook'
      fullPath: '/daybook'
      preLoaderRoute: typeof AuthenticatedDaybookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfer/': {
      id: '/_authenticated/transfer/'
      path: '/transfer'
      fullPath: '/transfer/'
      preLoaderRoute: typeof AuthenticatedTransferIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/storage/': {
      id: '/_authenticated/storage/'
      path: '/storage'
      fullPath: '/storage/'
      preLoaderRoute: typeof AuthenticatedStorageIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incoming/': {
      id: '/_authenticated/incoming/'
      path: '/incoming'
      fullPath: '/incoming/'
      preLoaderRoute: typeof AuthenticatedIncomingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grading/': {
      id: '/_authenticated/grading/'
      path: '/grading'
      fullPath: '/grading/'
      preLoaderRoute: typeof AuthenticatedGradingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/storage/$id': {
      id: '/_authenticated/storage/$id'
      path: '/storage/$id'
      fullPath: '/storage/$id'
      preLoaderRoute: typeof AuthenticatedStorageIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incoming/$id': {
      id: '/_authenticated/incoming/$id'
      path: '/incoming/$id'
      fullPath: '/incoming/$id'
      preLoaderRoute: typeof AuthenticatedIncomingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grading/$id': {
      id: '/_authenticated/grading/$id'
      path: '/grading/$id'
      fullPath: '/grading/$id'
      preLoaderRoute: typeof AuthenticatedGradingIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDaybookRoute: typeof AuthenticatedDaybookRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedGradingIdRoute: typeof AuthenticatedGradingIdRoute
  AuthenticatedIncomingIdRoute: typeof AuthenticatedIncomingIdRoute
  AuthenticatedStorageIdRoute: typeof AuthenticatedStorageIdRoute
  AuthenticatedGradingIndexRoute: typeof AuthenticatedGradingIndexRoute
  AuthenticatedIncomingIndexRoute: typeof AuthenticatedIncomingIndexRoute
  AuthenticatedStorageIndexRoute: typeof AuthenticatedStorageIndexRoute
  AuthenticatedTransferIndexRoute: typeof AuthenticatedTransferIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDaybookRoute: AuthenticatedDaybookRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedGradingIdRoute: AuthenticatedGradingIdRoute,
  AuthenticatedIncomingIdRoute: AuthenticatedIncomingIdRoute,
  AuthenticatedStorageIdRoute: AuthenticatedStorageIdRoute,
  AuthenticatedGradingIndexRoute: AuthenticatedGradingIndexRoute,
  AuthenticatedIncomingIndexRoute: AuthenticatedIncomingIndexRoute,
  AuthenticatedStorageIndexRoute: AuthenticatedStorageIndexRoute,
  AuthenticatedTransferIndexRoute: AuthenticatedTransferIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
